# -*- coding: utf-8 -*-
"""AI_Q2_Pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XgHDWSYyKZ2ZP7iP5SiWvEuQlgUVgUCB
"""

import pandas as pd

data = [
    [170, 65, 19, 85, 5],
    [180, 75, 20, 90, 6],
    [160, 55, 18, 80, 4],
    [175, 70, 21, 88, 7],
    [155, 50, 19, 82, 5],
    [165, 62, 22, 89, 6],
    [178, 80, 23, 91, 7],
    [162, 58, 20, 78, 3],
    [172, 68, 19, 86, 5],
    [169, 66, 20, 84, 4],
    [171, 64, 22, 87, 6],
    [177, 72, 21, 90, 9],
    [174, 76, 24, 88, 8],
    [158, 52, 18, 75, 3],
    [164, 63, 19, 81, 4]
]

#Question 2.1

df = pd.DataFrame(data, columns=['Height', 'Weight', 'Age', 'Avg_Grade', 'Courses'])

print(df)

#Question 2.2

df.describe()

#Question 2.3

count = df['Age'].value_counts()
print(count)

#Question 2.4

grade_filter = df[df.Avg_Grade > 85] #Filters the dataset of students based on grade
print(grade_filter)


age_filter=df[df.Age > 18] #Filters the dataset of students based on age
print(age_filter)


multi_filter=df[(df.Age > 18) & (df.Avg_Grade > 85)] #Filters the dataset of students based on age and grade
print(multi_filter)

#Question 2.3

group=df.groupby('Age')
print(group['Avg_Grade'].mean())